/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import org.joda.time.*;

/**
 *
 * @author office depot
 */
public class Desktop_Recepcionista extends javax.swing.JFrame {

    /**
     * Creates new form Recepcionista1
     */
    public Desktop_Recepcionista() {
        initComponents();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Recepcionista_Recepcionista_Salir_Btn = new javax.swing.JButton();
        Recepcionista_Recepcionista_Nombre_Lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Recepcionista_Recepcionista_Nombre_Lbl1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Recepcionista_Desktop_Inicio_Btn = new javax.swing.JButton();
        Recepcionista_Desktop_Cita_Btn = new javax.swing.JButton();
        Recepcionista_Desktop_Pacientes_Btn = new javax.swing.JButton();
        Recepcionista_Desktop_Agregar_Btn = new javax.swing.JButton();
        Recepcionista_Desktop_Editar_Btn = new javax.swing.JButton();
        Recepcionista_Inicio_Escritorio_Desktop = new javax.swing.JDesktopPane();

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamonos.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recepcionista1");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(1, 62, 45));

        Recepcionista_Recepcionista_Salir_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Recepcionista_Recepcionista_Salir_Btn.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Recepcionista_Recepcionista_Salir_Btn.setText("Salir");
        Recepcionista_Recepcionista_Salir_Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        Recepcionista_Recepcionista_Salir_Btn.setBorderPainted(false);
        Recepcionista_Recepcionista_Salir_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recepcionista_Recepcionista_Salir_BtnActionPerformed(evt);
            }
        });

        Recepcionista_Recepcionista_Nombre_Lbl.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Recepcionista_Recepcionista_Nombre_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista_Recepcionista_Nombre_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Recepcionista_Recepcionista_Nombre_Lbl.setText("Nombre del usuario");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/otro logo xd.png"))); // NOI18N

        Recepcionista_Recepcionista_Nombre_Lbl1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Recepcionista_Nombre_Lbl1.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista_Recepcionista_Nombre_Lbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Recepcionista_Recepcionista_Nombre_Lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vamonos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Recepcionista_Nombre_Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Recepcionista_Recepcionista_Nombre_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Recepcionista_Recepcionista_Salir_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Recepcionista_Recepcionista_Nombre_Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recepcionista_Recepcionista_Salir_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Recepcionista_Recepcionista_Nombre_Lbl))
                .addGap(39, 39, 39))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Recepcionista_Desktop_Inicio_Btn.setBackground(new java.awt.Color(29, 132, 99));
        Recepcionista_Desktop_Inicio_Btn.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        Recepcionista_Desktop_Inicio_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista_Desktop_Inicio_Btn.setText("Citas");
        Recepcionista_Desktop_Inicio_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recepcionista_Desktop_Inicio_BtnActionPerformed(evt);
            }
        });

        Recepcionista_Desktop_Cita_Btn.setBackground(new java.awt.Color(29, 132, 99));
        Recepcionista_Desktop_Cita_Btn.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        Recepcionista_Desktop_Cita_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista_Desktop_Cita_Btn.setText("Nueva cita");
        Recepcionista_Desktop_Cita_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recepcionista_Desktop_Cita_BtnActionPerformed(evt);
            }
        });

        Recepcionista_Desktop_Pacientes_Btn.setBackground(new java.awt.Color(29, 132, 99));
        Recepcionista_Desktop_Pacientes_Btn.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        Recepcionista_Desktop_Pacientes_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista_Desktop_Pacientes_Btn.setText("Pacientes");
        Recepcionista_Desktop_Pacientes_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recepcionista_Desktop_Pacientes_BtnActionPerformed(evt);
            }
        });

        Recepcionista_Desktop_Agregar_Btn.setBackground(new java.awt.Color(29, 132, 99));
        Recepcionista_Desktop_Agregar_Btn.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        Recepcionista_Desktop_Agregar_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista_Desktop_Agregar_Btn.setText("Agregar paciente");
        Recepcionista_Desktop_Agregar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recepcionista_Desktop_Agregar_BtnActionPerformed(evt);
            }
        });

        Recepcionista_Desktop_Editar_Btn.setBackground(new java.awt.Color(29, 132, 99));
        Recepcionista_Desktop_Editar_Btn.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        Recepcionista_Desktop_Editar_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Recepcionista_Desktop_Editar_Btn.setText("Editar Paciente");
        Recepcionista_Desktop_Editar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recepcionista_Desktop_Editar_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Recepcionista_Desktop_Editar_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(Recepcionista_Desktop_Agregar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(Recepcionista_Desktop_Pacientes_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Recepcionista_Desktop_Cita_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Recepcionista_Desktop_Inicio_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(Recepcionista_Desktop_Inicio_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recepcionista_Desktop_Cita_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recepcionista_Desktop_Pacientes_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recepcionista_Desktop_Agregar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recepcionista_Desktop_Editar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Recepcionista_Inicio_Escritorio_DesktopLayout = new javax.swing.GroupLayout(Recepcionista_Inicio_Escritorio_Desktop);
        Recepcionista_Inicio_Escritorio_Desktop.setLayout(Recepcionista_Inicio_Escritorio_DesktopLayout);
        Recepcionista_Inicio_Escritorio_DesktopLayout.setHorizontalGroup(
            Recepcionista_Inicio_Escritorio_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        Recepcionista_Inicio_Escritorio_DesktopLayout.setVerticalGroup(
            Recepcionista_Inicio_Escritorio_DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Recepcionista_Inicio_Escritorio_Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Recepcionista_Inicio_Escritorio_Desktop)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Recepcionista_Recepcionista_Salir_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recepcionista_Recepcionista_Salir_BtnActionPerformed
        
    }//GEN-LAST:event_Recepcionista_Recepcionista_Salir_BtnActionPerformed

    private void Recepcionista_Desktop_Inicio_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recepcionista_Desktop_Inicio_BtnActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_Recepcionista_Desktop_Inicio_BtnActionPerformed

    private void Recepcionista_Desktop_Cita_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recepcionista_Desktop_Cita_BtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Recepcionista_Desktop_Cita_BtnActionPerformed

    private void Recepcionista_Desktop_Agregar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recepcionista_Desktop_Agregar_BtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Recepcionista_Desktop_Agregar_BtnActionPerformed

    private void Recepcionista_Desktop_Editar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recepcionista_Desktop_Editar_BtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Recepcionista_Desktop_Editar_BtnActionPerformed

    private void Recepcionista_Desktop_Pacientes_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recepcionista_Desktop_Pacientes_BtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Recepcionista_Desktop_Pacientes_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop_Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop_Recepcionista().setVisible(true);
                
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Recepcionista_Desktop_Agregar_Btn;
    public javax.swing.JButton Recepcionista_Desktop_Cita_Btn;
    public javax.swing.JButton Recepcionista_Desktop_Editar_Btn;
    public javax.swing.JButton Recepcionista_Desktop_Inicio_Btn;
    public javax.swing.JButton Recepcionista_Desktop_Pacientes_Btn;
    public javax.swing.JDesktopPane Recepcionista_Inicio_Escritorio_Desktop;
    public javax.swing.JLabel Recepcionista_Recepcionista_Nombre_Lbl;
    public javax.swing.JLabel Recepcionista_Recepcionista_Nombre_Lbl1;
    public javax.swing.JButton Recepcionista_Recepcionista_Salir_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
