/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import org.joda.time.*;

/**
 *
 * @author office depot
 */
public class IF_AdministradorUtensilios extends javax.swing.JInternalFrame {

    /**
     * Creates new form ZZZ_InternalFrame_DoctorCita
     */
    public IF_AdministradorUtensilios() {
        initComponents();
        this.setLocation(-6, -25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Administrador_Utensilios_Insertar_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Administrador_Utensilios_TablaCitas_Table = new javax.swing.JTable();
        Administrador_Utensilios_TablaCitas_Table.getTableHeader().setFont(new Font("Calibri", Font.PLAIN, 24));
        jLabel8 = new javax.swing.JLabel();
        Administrador_Utensilios_OrdenarPor_CBox = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        jLabel133 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(10);
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Administrador_Utensilios_IdRegistroUtensilios_Txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Administrador_Utensilios_Cantidad_Txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Administrador_Utensilios_IdArticulo_Txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Administrador_Utensilios_IdCita_Txt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Administrador_Utensilios_Existencia_Txt = new javax.swing.JTextField();
        Administrador_Utensilios_Incremento_CBox = new javax.swing.JSpinner();
        Administrador_Utensilios_Actualizar_Btn = new javax.swing.JButton();
        Administrador_Utensilios_Eliminar_Btn = new javax.swing.JButton();
        Administrador_Utensilios_Limpira_Btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Administrador_Utensilios_TablaUtensilios_Table = new javax.swing.JTable();
        Administrador_Utensilios_TablaCitas_Table.getTableHeader().setFont(new Font("Calibri", Font.PLAIN, 24));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel6.setBackground(new java.awt.Color(29, 132, 99));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Utensilios");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        Administrador_Utensilios_Insertar_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Administrador_Utensilios_Insertar_Btn.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Administrador_Utensilios_Insertar_Btn.setText("Insertar");
        Administrador_Utensilios_Insertar_Btn.setActionCommand("");
        Administrador_Utensilios_Insertar_Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        Administrador_Utensilios_Insertar_Btn.setBorderPainted(false);
        Administrador_Utensilios_Insertar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administrador_Utensilios_Insertar_BtnActionPerformed(evt);
            }
        });

        Administrador_Utensilios_TablaCitas_Table.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_TablaCitas_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id utensilios", "Artículo", "Id cita", "CURP del doctor de la cita", "Fecha de la cita"
            }
        ));
        Administrador_Utensilios_TablaCitas_Table.setRowHeight(24);
        jScrollPane1.setViewportView(Administrador_Utensilios_TablaCitas_Table);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setText("Ordenar por:");

        Administrador_Utensilios_OrdenarPor_CBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_OrdenarPor_CBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id cita", "CURP doctor"}));

        jPanel21.setBackground(new java.awt.Color(29, 132, 99));
        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel133.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(255, 255, 255));
        jLabel133.setText("Información del utensilio utilizado");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel10.setText("Id del registro de utensilios:");

        Administrador_Utensilios_IdRegistroUtensilios_Txt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_IdRegistroUtensilios_Txt.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel15.setText("Cantidad:");

        Administrador_Utensilios_Cantidad_Txt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_Cantidad_Txt.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel16.setText("Id Articulo");

        Administrador_Utensilios_IdArticulo_Txt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_IdArticulo_Txt.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel13.setText("Id de la cita:");

        Administrador_Utensilios_IdCita_Txt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_IdCita_Txt.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel17.setText("Incrementar cantidad:");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel18.setText("Existencia:");

        Administrador_Utensilios_Existencia_Txt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_Existencia_Txt.setEnabled(false);

        Administrador_Utensilios_Incremento_CBox.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Administrador_Utensilios_Cantidad_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Administrador_Utensilios_Existencia_Txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Administrador_Utensilios_IdArticulo_Txt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Administrador_Utensilios_Incremento_CBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Administrador_Utensilios_IdRegistroUtensilios_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Administrador_Utensilios_IdCita_Txt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Administrador_Utensilios_IdRegistroUtensilios_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Administrador_Utensilios_IdCita_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Administrador_Utensilios_IdArticulo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(Administrador_Utensilios_Existencia_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(Administrador_Utensilios_Cantidad_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Administrador_Utensilios_Incremento_CBox, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel133)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel133)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Administrador_Utensilios_Actualizar_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Administrador_Utensilios_Actualizar_Btn.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Administrador_Utensilios_Actualizar_Btn.setText("Actualizar");
        Administrador_Utensilios_Actualizar_Btn.setActionCommand("");
        Administrador_Utensilios_Actualizar_Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        Administrador_Utensilios_Actualizar_Btn.setBorderPainted(false);
        Administrador_Utensilios_Actualizar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administrador_Utensilios_Actualizar_BtnActionPerformed(evt);
            }
        });

        Administrador_Utensilios_Eliminar_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Administrador_Utensilios_Eliminar_Btn.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Administrador_Utensilios_Eliminar_Btn.setText("Eliminar");
        Administrador_Utensilios_Eliminar_Btn.setActionCommand("");
        Administrador_Utensilios_Eliminar_Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        Administrador_Utensilios_Eliminar_Btn.setBorderPainted(false);
        Administrador_Utensilios_Eliminar_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administrador_Utensilios_Eliminar_BtnActionPerformed(evt);
            }
        });

        Administrador_Utensilios_Limpira_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Administrador_Utensilios_Limpira_Btn.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Administrador_Utensilios_Limpira_Btn.setText("Limpiar");
        Administrador_Utensilios_Limpira_Btn.setActionCommand("");
        Administrador_Utensilios_Limpira_Btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        Administrador_Utensilios_Limpira_Btn.setBorderPainted(false);
        Administrador_Utensilios_Limpira_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administrador_Utensilios_Limpira_BtnActionPerformed(evt);
            }
        });

        Administrador_Utensilios_TablaUtensilios_Table.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Administrador_Utensilios_TablaUtensilios_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id utensilios", "Artículo"
            }
        ));
        Administrador_Utensilios_TablaUtensilios_Table.setRowHeight(24);
        jScrollPane3.setViewportView(Administrador_Utensilios_TablaUtensilios_Table);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Administrador_Utensilios_OrdenarPor_CBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(Administrador_Utensilios_Limpira_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Administrador_Utensilios_Eliminar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Administrador_Utensilios_Actualizar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Administrador_Utensilios_Insertar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Administrador_Utensilios_OrdenarPor_CBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Administrador_Utensilios_Insertar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Administrador_Utensilios_Actualizar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Administrador_Utensilios_Eliminar_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Administrador_Utensilios_Limpira_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Administrador_Utensilios_Insertar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administrador_Utensilios_Insertar_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Administrador_Utensilios_Insertar_BtnActionPerformed

    private void Administrador_Utensilios_Actualizar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administrador_Utensilios_Actualizar_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Administrador_Utensilios_Actualizar_BtnActionPerformed

    private void Administrador_Utensilios_Eliminar_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administrador_Utensilios_Eliminar_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Administrador_Utensilios_Eliminar_BtnActionPerformed

    private void Administrador_Utensilios_Limpira_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administrador_Utensilios_Limpira_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Administrador_Utensilios_Limpira_BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Administrador_Utensilios_Actualizar_Btn;
    public javax.swing.JTextField Administrador_Utensilios_Cantidad_Txt;
    public javax.swing.JButton Administrador_Utensilios_Eliminar_Btn;
    public javax.swing.JTextField Administrador_Utensilios_Existencia_Txt;
    public javax.swing.JTextField Administrador_Utensilios_IdArticulo_Txt;
    public javax.swing.JTextField Administrador_Utensilios_IdCita_Txt;
    public javax.swing.JTextField Administrador_Utensilios_IdRegistroUtensilios_Txt;
    public javax.swing.JSpinner Administrador_Utensilios_Incremento_CBox;
    public javax.swing.JButton Administrador_Utensilios_Insertar_Btn;
    public javax.swing.JButton Administrador_Utensilios_Limpira_Btn;
    public javax.swing.JComboBox<String> Administrador_Utensilios_OrdenarPor_CBox;
    public javax.swing.JTable Administrador_Utensilios_TablaCitas_Table;
    public javax.swing.JTable Administrador_Utensilios_TablaUtensilios_Table;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
