/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

 
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import org.joda.time.*;
/**
 *
 * @author Daniela Ramírez
 */
public class IF_DoctorEditarPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form internalDocEditPac
     */
    public IF_DoctorEditarPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Doctor_EditarPacientes_TablaCitas_table = new javax.swing.JTable();
        Doctor_EditarPacientes_TablaCitas_table.getTableHeader().setFont(new Font("Calibri", Font.PLAIN, 24));
        jLabel5 = new javax.swing.JLabel();
        Doctor_EditarPacientes_Mostrar_CBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Doctor_EditarPacientes_Ordenar_CBox = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        jLabel133 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane9.getVerticalScrollBar().setUnitIncrement(10);
        jPanel20 = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        Doctor_EditarPacientes_Id_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_Genero_CBox = new javax.swing.JComboBox<>();
        Doctor_EditarPacientes_EstadoC_CBox = new javax.swing.JComboBox<>();
        Doctor_EditarPacientes_Curp_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_Correo_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_Direccion_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_Celular_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_Telefono_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_FechaN_DPicker = new org.jdesktop.swingx.JXDatePicker();
        Doctor_EditarPacientes_FechaN_DPicker.setFormats( new String[] {"dd/MM/yyyy"});
        Doctor_EditarPacientes_FechaN_DPicker.setLinkDate(System.currentTimeMillis(), "Hoy es: {0}");
        Doctor_EditarPacientes_FechaN_DPicker.setFont(new Font("Calibri", Font.PLAIN, 24));
        jLabel135 = new javax.swing.JLabel();
        Doctor_EditarPacientes_PApell_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_MApell_Txt = new javax.swing.JTextField();
        jLabel136 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        Doctor_EditarPacientes_Nombre_Txt = new javax.swing.JTextField();
        jLabel139 = new javax.swing.JLabel();
        Doctor_EditarPacientes_Edad_Txt = new javax.swing.JTextField();
        Doctor_EditarPacientes_GuardarCambios_Btn = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel6.setBackground(new java.awt.Color(29, 132, 99));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pacientes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        Doctor_EditarPacientes_TablaCitas_table.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Doctor_EditarPacientes_TablaCitas_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Edad", "CURP"
            }
        ));
        Doctor_EditarPacientes_TablaCitas_table.setRowHeight(24);
        jScrollPane1.setViewportView(Doctor_EditarPacientes_TablaCitas_table);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("Mostrar:");

        Doctor_EditarPacientes_Mostrar_CBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Doctor_EditarPacientes_Mostrar_CBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Mujeres", "Hombres"}));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setText("Ordenar por:");

        Doctor_EditarPacientes_Ordenar_CBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Doctor_EditarPacientes_Ordenar_CBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apellido", "Edad", "Registro"}));

        jPanel21.setBackground(new java.awt.Color(29, 132, 99));
        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel133.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(255, 255, 255));
        jLabel133.setText("Informacion de paciente");

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel134.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel134.setText("Id");

        jLabel137.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel137.setText("Fecha de nacimiento");

        jLabel141.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel141.setText("Correo");

        jLabel143.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel143.setText("Dirección");

        jLabel145.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel145.setText("Telefono");

        jLabel147.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel147.setText("Celular");

        jLabel148.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel148.setText("Genero");

        jLabel150.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel150.setText("Estado civil");

        jLabel152.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel152.setText("CURP");

        Doctor_EditarPacientes_Id_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Doctor_EditarPacientes_Id_Txt.setEnabled(false);

        Doctor_EditarPacientes_Genero_CBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Doctor_EditarPacientes_Genero_CBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        Doctor_EditarPacientes_EstadoC_CBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Doctor_EditarPacientes_EstadoC_CBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Viudo", "Divorciado" }));

        Doctor_EditarPacientes_Curp_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        Doctor_EditarPacientes_Correo_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        Doctor_EditarPacientes_Direccion_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        Doctor_EditarPacientes_Celular_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Doctor_EditarPacientes_Celular_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_EditarPacientes_Celular_TxtActionPerformed(evt);
            }
        });

        Doctor_EditarPacientes_Telefono_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        Doctor_EditarPacientes_FechaN_DPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_EditarPacientes_FechaN_DPickerActionPerformed(evt);
            }
        });

        jLabel135.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel135.setText("Apellido paterno");

        Doctor_EditarPacientes_PApell_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        Doctor_EditarPacientes_MApell_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel136.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel136.setText(" Apellido materno");

        jLabel138.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel138.setText("Nombre");

        Doctor_EditarPacientes_Nombre_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel139.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel139.setText("Edad");

        Doctor_EditarPacientes_Edad_Txt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Doctor_EditarPacientes_Edad_Txt.setEnabled(false);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel138)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Nombre_Txt))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel134)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Id_Txt))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel135)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_PApell_Txt))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel136)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_MApell_Txt))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel137)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_FechaN_DPicker, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel139)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Edad_Txt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel148)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Genero_CBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel150)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_EstadoC_CBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel152)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Curp_Txt))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel143)
                            .addComponent(jLabel145))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Doctor_EditarPacientes_Telefono_Txt)
                            .addComponent(Doctor_EditarPacientes_Direccion_Txt)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel141)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Correo_Txt))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel147)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Celular_Txt)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Id_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel134))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Nombre_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel138))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_PApell_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel135))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_MApell_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel136))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_FechaN_DPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel137))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Edad_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel139))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Genero_CBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel148))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_EstadoC_CBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel150))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Curp_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel152))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Correo_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel141))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Direccion_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel143))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Telefono_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel145))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_EditarPacientes_Celular_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel147))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane9.setViewportView(jPanel20);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel133)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel133)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Doctor_EditarPacientes_GuardarCambios_Btn.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Doctor_EditarPacientes_GuardarCambios_Btn.setText("Guardar cambios");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Doctor_EditarPacientes_GuardarCambios_Btn)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Mostrar_CBox, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_EditarPacientes_Ordenar_CBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Doctor_EditarPacientes_Mostrar_CBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(Doctor_EditarPacientes_Ordenar_CBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Doctor_EditarPacientes_GuardarCambios_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Doctor_EditarPacientes_FechaN_DPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_EditarPacientes_FechaN_DPickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Doctor_EditarPacientes_FechaN_DPickerActionPerformed

    private void Doctor_EditarPacientes_Celular_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_EditarPacientes_Celular_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Doctor_EditarPacientes_Celular_TxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Doctor_EditarPacientes_Celular_Txt;
    public javax.swing.JTextField Doctor_EditarPacientes_Correo_Txt;
    public javax.swing.JTextField Doctor_EditarPacientes_Curp_Txt;
    public javax.swing.JTextField Doctor_EditarPacientes_Direccion_Txt;
    public javax.swing.JTextField Doctor_EditarPacientes_Edad_Txt;
    public javax.swing.JComboBox<String> Doctor_EditarPacientes_EstadoC_CBox;
    public org.jdesktop.swingx.JXDatePicker Doctor_EditarPacientes_FechaN_DPicker;
    public javax.swing.JComboBox<String> Doctor_EditarPacientes_Genero_CBox;
    public javax.swing.JButton Doctor_EditarPacientes_GuardarCambios_Btn;
    public javax.swing.JTextField Doctor_EditarPacientes_Id_Txt;
    public javax.swing.JTextField Doctor_EditarPacientes_MApell_Txt;
    public javax.swing.JComboBox<String> Doctor_EditarPacientes_Mostrar_CBox;
    public javax.swing.JTextField Doctor_EditarPacientes_Nombre_Txt;
    public javax.swing.JComboBox<String> Doctor_EditarPacientes_Ordenar_CBox;
    public javax.swing.JTextField Doctor_EditarPacientes_PApell_Txt;
    public javax.swing.JTable Doctor_EditarPacientes_TablaCitas_table;
    public javax.swing.JTextField Doctor_EditarPacientes_Telefono_Txt;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
