/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import org.joda.time.*;
/**
 *
 * @author Daniela Ramírez
 */
public class IF_RecepcionistaPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pacientes
     */
    public IF_RecepcionistaPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Recepcionista_Pacientes_TablaPacientes_Table = new javax.swing.JTable();
        Recepcionista_Pacientes_TablaPacientes_Table.getTableHeader().setFont(new Font("Calibri", Font.PLAIN, 24));
        jPanel21 = new javax.swing.JPanel();
        jLabel133 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane9.getVerticalScrollBar().setUnitIncrement(10);
        jPanel20 = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Nombre_Lbl = new javax.swing.JLabel();
        Recepcionista_Pacientes_FechaN_Lbl = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Edad_Lbl = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Correo_Lbl = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Direccion_Lbl = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Telefono_Lbl = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Celular_Lbl = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Genero_Lbl = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        Recepcionista_Pacientes_EstadoCivil_Lbl = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        Recepcionista_Pacientes_Curp_Lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Recepcionista_Pacientes_ApellidoPaterno_Lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Recepcionista_Pacientes_ApellidoMaterno_Lbl = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel6.setBackground(new java.awt.Color(29, 132, 99));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Información pacientes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        Recepcionista_Pacientes_TablaPacientes_Table.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Recepcionista_Pacientes_TablaPacientes_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "CURP"
            }
        ));
        Recepcionista_Pacientes_TablaPacientes_Table.setRowHeight(24);
        jScrollPane1.setViewportView(Recepcionista_Pacientes_TablaPacientes_Table);

        jPanel21.setBackground(new java.awt.Color(29, 132, 99));
        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel133.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(255, 255, 255));
        jLabel133.setText("Informacion de paciente");

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel134.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel134.setText("Nombre");

        Recepcionista_Pacientes_Nombre_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Nombre_Lbl.setText("[nombre aqui]");

        Recepcionista_Pacientes_FechaN_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_FechaN_Lbl.setText("[fecha aqui]");

        jLabel137.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel137.setText("Fecha de nacimiento");

        Recepcionista_Pacientes_Edad_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Edad_Lbl.setText("[edad aqui]");

        jLabel139.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel139.setText("Edad");

        Recepcionista_Pacientes_Correo_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Correo_Lbl.setText("[correo aqui]");

        jLabel141.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel141.setText("Correo");

        Recepcionista_Pacientes_Direccion_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Direccion_Lbl.setText("[direccion aqui]");

        jLabel143.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel143.setText("Dirección");

        Recepcionista_Pacientes_Telefono_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Telefono_Lbl.setText("[telefono aqui]");

        jLabel145.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel145.setText("Telefono");

        Recepcionista_Pacientes_Celular_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Celular_Lbl.setText("[celular aqui]");

        jLabel147.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel147.setText("Celular");

        jLabel148.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel148.setText("Genero");

        Recepcionista_Pacientes_Genero_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Genero_Lbl.setText("[genero aqui]");

        jLabel150.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel150.setText("Estado civil");

        Recepcionista_Pacientes_EstadoCivil_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_EstadoCivil_Lbl.setText("[estado civil aqui]");

        jLabel152.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel152.setText("CURP");

        Recepcionista_Pacientes_Curp_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_Curp_Lbl.setText("[curp aqui]");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Apellido paterno");

        Recepcionista_Pacientes_ApellidoPaterno_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_ApellidoPaterno_Lbl.setText("[Apellido paterno aqui]");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Apellido materno");

        Recepcionista_Pacientes_ApellidoMaterno_Lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Recepcionista_Pacientes_ApellidoMaterno_Lbl.setText("[Apellido materno aqui]");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Recepcionista_Pacientes_Nombre_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_FechaN_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_Edad_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_Genero_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_EstadoCivil_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_Curp_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_Correo_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_Direccion_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_Telefono_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_Celular_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recepcionista_Pacientes_ApellidoPaterno_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel134)
                            .addComponent(jLabel137)
                            .addComponent(jLabel139)
                            .addComponent(jLabel148)
                            .addComponent(jLabel150)
                            .addComponent(jLabel152)
                            .addComponent(jLabel141)
                            .addComponent(jLabel143)
                            .addComponent(jLabel145)
                            .addComponent(jLabel147)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(Recepcionista_Pacientes_ApellidoMaterno_Lbl))
                        .addGap(0, 542, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel134)
                .addGap(2, 2, 2)
                .addComponent(Recepcionista_Pacientes_Nombre_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_ApellidoPaterno_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Recepcionista_Pacientes_ApellidoMaterno_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel137)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_FechaN_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel139)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_Edad_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel148)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_Genero_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel150)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_EstadoCivil_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel152)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_Curp_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel141)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_Correo_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel143)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_Direccion_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel145)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_Telefono_Lbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel147)
                .addGap(18, 18, 18)
                .addComponent(Recepcionista_Pacientes_Celular_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane9.setViewportView(jPanel20);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel133)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel133)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Recepcionista_Pacientes_ApellidoMaterno_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_ApellidoPaterno_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_Celular_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_Correo_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_Curp_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_Direccion_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_Edad_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_EstadoCivil_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_FechaN_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_Genero_Lbl;
    public javax.swing.JLabel Recepcionista_Pacientes_Nombre_Lbl;
    public javax.swing.JTable Recepcionista_Pacientes_TablaPacientes_Table;
    public javax.swing.JLabel Recepcionista_Pacientes_Telefono_Lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
